### ISSUE TITLE
RRfilter function: filtering steps

### ISSUE THREAD

**Issue by agostontorok** [MarcusVollmer/HRV#2]
Hi, I was trying to figure out the filtering steps of RRfilter, but would really use some help either in the form of comments to the parts of the code and/or explanations here. 

So in my reading there are four steps.
- RR spike detection

`RR(rr_pct>max([limit 50]) & [rr_pct(2:end)<-max([limit 50]); false]) = NaN; 
`
- Detect wrong beat positions
  - why is it in a loop? 
  - What is a wrong beat position?
  - why is it > wbp(diff(wbp)==1) < called (only) twice?

```
for wbp_lim = [80:-10:limit]-rem(limit,10)
        wbp = find(abs(diff(rr_pct))>wbp_lim);    %wbp is the index of the beat changes over the limit
        wbp = wbp(diff(wbp)==1); %two consecutive values
        wbp = wbp(diff(wbp)==1); %three consecutive values 
        RR(wbp+1) = NaN; RR(wbp+2) = NaN; %wrong beat positions
        rr_pct = 100*HRV.rrx(RR); 
    end
```
- Strange values after a NaN
  - Why is it hardcoded 15%?
  - What does postmp stands for?

```
postmp = find(isnan(RR(1:(end-2))));
RR(postmp(abs(rr_pct(postmp+2))>15)+1) = NaN; %unreasonble differences after NaN-values
```
- Discard unreasonable values left in the data
  - Why isn't this the only part?
  - Why is it hardcoded to 50?

```
postmp = find(abs(rr_pct)>max([limit 50]));
RR(postmp-1) = NaN; RR(postmp) = NaN; %unreasonble rr_pct values
```

I would like to add, that this a very nice package with very useful features. Keep up the good work!

**Comment by MarcusVollmer** [comment]
Hi Ágoston,

thanks for your detailed questions according the filtering method, which is was broached on [Manual#Filtering](http://marcusvollmer.github.io/HRV/manual_english.html#filtering). Indeed the procedure seems to be a bit unfounded. I want to give you some more details. 

To motivate the following, I will answer your question first, why I don't discard unreasonable values just by searching for the positions (postmp means temporary position) and replace it with NaNs:
```
postmp = find(abs(rr_pct)>limit);
RR(postmp) = NaN;
```
The reason is simple: It would replace correct intervals, too. Imagine the heart pauses or the detection failed for three seconds: RR=[1 1 3 1 1]. The corresponding relative RR intervals are rr=[NaN 0 1 -1 0]. Applying the simplest rule above, the algorithm would also replace the correct interval which follows the pause.

This is also the motivation for the first step of my procedure:
`RR(rr_pct>max([limit 50]) & [rr_pct(2:end)<-max([limit 50]); false]) = NaN; `

Reading this line of code carefully we will realize that this refers to a very special case of a "spike". The relative change must be positive at first (at least 50%) and negative (less than -50%) as the second. Then only the long interval can be clearly identified as an abnormal interval. So cases of isolated pauses are covered.

So what else can happen? Please take a look on this figure
![cases](https://cloud.githubusercontent.com/assets/8678170/16616430/85578bbc-437d-11e6-8a0c-8eb631f16c57.png)
It shows some typical RR sequences with either artefacts or arrhythmias. The intervals are in seconds with corresponding relative changes in percent. The case of a wrong heart beat position is printed as case D. A heart beat moved forward and caused a short interval (0.41s), followed by a longer interval (0.83s). Without the information of the waveform we cannot determine whether this was a mistake of the heart beat detector or whether this was a real extrasystole followed by a compensatory pause. In both cases the two affected intervals should be removed from the analysis of heart rate variability.

Please take a look now on the inner part of the loop:
```
wbp = find(abs(diff(rr_pct))>wbp_lim);    %wbp is the index of the beat changes over the limit
wbp = wbp(diff(wbp)==1); %two consecutive values
wbp = wbp(diff(wbp)==1); %three consecutive values 
RR(wbp+1) = NaN; RR(wbp+2) = NaN; %wrong beat positions
```
It says the following for wbp_lim=20%: 

- Replace RR_i and RR_{i+1} with NaN if |rr_i −rr_{i−1} |>20% and |rr_{i+1} −rr_i |>20% and |rr_{i+2} −rr_{i+1} |>20%. This will manage extrasystoles or misplaced heart beats (cases B,C,D of the figure).

`wbp = find(abs(diff(rr_pct))>wbp_lim);` computes the time points when the difference goes beyond the limit.  But there must be three consecutive relative RR intervals which differ at least 20%. So calling `wbp = wbp(diff(wbp)==1); ` twice will do the job instead of searching for a subvector of three successive values.

Without the loop the procedure will also remove the first correct RR interval directly after probably incorrect intervals. For example in this case:
```
RR = [0.773 0.773 0.789 0.445 1.078 0.797 0.773]
rr = [NaN 0.000 0.020 -0.557 0.831 -0.300 -0.030]
```
A loop is not the most elegant way to handles these issues, but by now I am quite satisfied how the filtering works.

When you look at case example E there is wrong interval directly after the pause. This has induced me to check the intervals after already replaced RR intervals, which is indeed very hardcoded (only 15% tolerance):
```
postmp = find(isnan(RR(1:(end-2))));
RR(postmp(abs(rr_pct(postmp+2))>15)+1) = NaN;
```

I hope you was able to follow my steps. Please do not hesitate to ask further questions.

Best,
Marcus
